"""Documented default thresholds for deterministic maintainability smells."""

LONG_FUNCTION_SLOC = 50
DEEP_NESTING_DEPTH = 4
HIGH_COMPLEXITY = 11
TOO_MANY_PARAMETERS = 5
COMPLEX_BOOLEAN_LEAVES = 4
OVERSIZED_PROCEDURAL_SLOC = 50
EXCESSIVE_TOP_LEVEL_STATEMENTS = 30
